name: BuildAndRunTests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - ObjectPath/source/**
  pull_request:
    branches: [ "main" ]
    paths:
    - source/**
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ObjectPath
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore source/ObjectPath.sln 

    - name: Build
      run: dotnet build --no-restore source/ObjectPath.sln --property WarningLevel=0
      
    - name: Test
      run: dotnet test --no-build --verbosity normal source/ObjectPath.sln
